language: go

go:
  - 1.5
  - 1.5.1
  - tip

before_install:
  - go get github.com/mattn/gom

script:
  - go clean -i
  - $HOME/gopath/bin/gom install
  - base=$(pwd)

matrix:
  allow_failures:
    - go: tip
