language: go

go:
  - 1.5.1
  - tip

before_install:
  - go get github.com/mattn/gom

script:
  - $HOME/gopath/bin/gom install
  - base=$(pwd)
  - cd "$base/request"; $HOME/gopath/bin/gom test
  - cd "$base/response"; $HOME/gopath/bin/gom test
  - cd "$base/environment"; $HOME/gopath/bin/gom test

matrix:
  allow_failures:
    - go: tip
